### ISSUE TITLE
doxygen build warnings

### ISSUE THREAD

**Issue by xross** [xmos/lib_gpio#3]
/buildbot_worker/DailyVocalFusion_xmos_docker/build/sb/lib_gpio/lib_gpio/doc/rst/_build/.doxygen/api/gpio.h:79: Warning: argument 'pin_map' of command @param is not found in the argument list of output_gpio(server output_gpio_if i[n], static const size_t n, out port p, char(&?pin_map)[n])
    /buildbot_worker/DailyVocalFusion_xmos_docker/build/sb/lib_gpio/lib_gpio/doc/rst/_build/.doxygen/api/gpio.h:98: Warning: argument 'pin_map' of command @param is not found in the argument list of input_gpio(server input_gpio_if i[n], static const size_t n, in port p, char(&?pin_map)[n])

**Comment by mbanth** [comment]
Jenkins runs of the [HEAD of develop on 13 Dec 2020 at 20:00](http://srv-bri-jcim0:8080/job/XMOS/job/lib_gpio/job/develop/426/console) and the [HEAD of master on 08 Oct 2020 at 12:52](http://srv-bri-jcim0:8080/job/XMOS/job/lib_gpio/job/master/13/console) do not produce this warning.  The invocation of Doxygen produces no warnings or errors.
